spring.datasource.url=jdbc:h2:mem:taskmanagerdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=samawnd
spring.datasource.password=samasama

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create

spring.h2.console.enabled=true
spring.h2.console.path=/taskmanagerdb

server.port=8081

jwt.secret=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
jwt.expiration=3600000

# database
# http://localhost:8081/taskmanagerdb

# swagger doc
#http://localhost:8081/swagger-ui/index.html