spring.application.name=myTaskmanager

# jdbc:h2 is type of the database (h2)
# mem means in memory ( so it wil be rmeoved when it stops)
spring.datasource.url=jdbc:h2:mem:taskmanagerdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=samawnd
spring.datasource.password=samasama

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create

spring.h2.console.enabled=true

# http://localhost:8080/taskmanagerdb
spring.h2.console.path=/taskmanagerdb

#http://localhost:8080/swagger-ui/index.html swagger

jwt.secret=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
jwt.expiration=3600000  